services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - redis
      - db

  redis:
    image: redis

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password