name: Push

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Ducker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOUCKERHUB_USERNAME }}
          password: ${{ secrets.DOUCKERHUB_TOKEN }}
  build-and-push-image:
    steps:
        - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            mhndgh/flask:latest
            mhndgh/flask:${{ github.sha }}
